console.log ('data.js connected');

const maleCelebrity = [{name: 'Brad Pitt', 
img: 'https://beardoholic.com/wp-content/uploads/2018/01/brad_pitt-721a5984-ae2e-4340-a81e-8f8831d584db.jpg'}, 
{name: 'Humphrey Bogart', 
img: 'http://humphreybogart.com/wp-content/uploads/2015/03/villainhero.jpg'}, 
{name: 'Robert Downey, Jr.', 
img:'https://www.nzherald.co.nz/resizer/RHS5wnoxsNTlOeOXpK17jpJHJAo=/360x384/filters:quality(70)/arc-anglerfish-syd-prod-nzme.s3.amazonaws.com/public/SQHCWQ4JUND5VA6EBDESXK6LQI.jpg'}, 
{name: 'Leonardo DiCaprio', 
img: 'https://m.media-amazon.com/images/M/MV5BMjI0MTg3MzI0M15BMl5BanBnXkFtZTcwMzQyODU2Mw@@._V1_UY317_CR10,0,214,317_AL_.jpg'}, 
{name: 'Johnny Depp', 
img: 'https://m.media-amazon.com/images/M/MV5BMTM0ODU5Nzk2OV5BMl5BanBnXkFtZTcwMzI2ODgyNQ@@._V1_.jpg'}, 
{name: 'George Clooney', 
img:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/George_Clooney_2016.jpg/220px-George_Clooney_2016.jpg'}, 
{name: 'Heath Ledger', 
img: 'https://www.intouchweekly.com/wp-content/uploads/2017/08/heath-ledger-death-teaser.jpg?fit=200%2C1'}, 
{name: 'Alan Rickman', 
img:'https://m.media-amazon.com/images/M/MV5BMTUwNTc4MTg4Ml5BMl5BanBnXkFtZTcwNDY2MjkxOA@@._V1_.jpg'}, 
{name: 'Bill Paxton', 
img: 'https://cdn.cnn.com/cnnnext/dam/assets/170226103633-02-bill-paxton-exlarge-169.jpg'}, 
{name: 'Robin Williams', 
img: 'https://secure.i.telegraph.co.uk/multimedia/archive/03003/robinWilliams_3003215k.jpg'}];


const femaleCelebrity = [{name: 'Jennifer Lawrence', 
img:'https://timedotcom.files.wordpress.com/2015/01/jennifer-lawrence.jpg'}, 
{name: 'Natalie Portman', 
img: 'https://timedotcom.files.wordpress.com/2015/05/natalie-portman.jpg'}, {name:'Emma Watson', 
img: 'https://hdwallsource.com/img/2014/9/beautiful-emma-watson-42945-43969-hd-wallpapers.jpg'}, 
{name: 'Emma Stone', 
img: 'https://m.media-amazon.com/images/M/MV5BMjI4NjM1NDkyN15BMl5BanBnXkFtZTgwODgyNTY1MjE@._V1..jpg'}, 
{name:'Scarlett Johansson', 
img:'https://m.media-amazon.com/images/M/MV5BMTM3OTUwMDYwNl5BMl5BanBnXkFtZTcwNTUyNzc3Nw@@._V1_.jpg'}, 
{name:'Meryl Streep', 
img:'https://m.media-amazon.com/images/M/MV5BMTU4Mjk5MDExOF5BMl5BanBnXkFtZTcwOTU1MTMyMw@@._V1_UY317_CR6,0,214,317_AL_.jpg'}, 
{name:'Charlize Theron', 
img:'https://pixel.nymag.com/imgs/fashion/daily/2016/04/05/05-charlize-theron.w330.h412.jpg'}, 
{name:'Mila Kunis', 
img:'https://m.media-amazon.com/images/M/MV5BODQyNTQyNzY4MV5BMl5BanBnXkFtZTcwODg5MDA3MQ@@._V1_UY317_CR25,0,214,317_AL_.jpg'}, 
{name:'Jennifer Aniston', 
img:'http://upload.wikimedia.org/wikipedia/commons/thumb/1/16/JenniferAnistonHWoFFeb2012.jpg/220px-JenniferAnistonHWoFFeb2012.jpg'}, 
{name:'Anne Hathaway', 
img:'https://cdn.newsapi.com.au/image/v1/9348593d5c18dbe8ba0d260b1813b85d'}];